### ISSUE TITLE
The import path for include-media is invalid.

### ISSUE THREAD

**Issue by sniederhumer** [davidhellmann/baukasten-grid#5]
The current version `3.0.0` available via npm is not usable, since the import of `include-media` in `baukasten-grid.scss` is invalid. 

Current version:
```scss
@import '../node_modules/include-media/dist/include-media';
```

Should be:
```scss
@import '~include-media/dist/include-media';
```

**Comment by davidhellmann** [comment]
Hey @sniederhumer 
fixed some paths and I use it currently in a project and looks fine. But V3 is hard cut to v2. Its more UT Classes driven.
